//University
List<String> departments = [
  "Accounting",
  "Architecture",
  "Business Administration",
  "Civil Engineering",
  "Computer Science and Engineering",
  "Economics",
  "Electrical and Electronic Engineering",
  "English",
  "Law",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Pharmacy",
  "Physics",
  "Political Science",
  "Public Administration",
  "Sociology",
  "Statistics",
];

//BCS
List<String> cadres = [
  "Administration Cadre",
  "Police Cadre",
  "Foreign Affairs Cadre",
  "Audit and Accounts Cadre",
  "Information Cadre",
  "Taxation Cadre",
  "Cooperative Cadre",
  "Health Cadre",
];

Map<String, List<String>> subjects = {
  "Administration Cadre": [
    "Bangla",
    "English",
    "Bangladesh Affairs",
    "International Affairs",
    "Mental Ability",
    "General Science and Technology",
    "Mathematical Reasoning",
  ],
  "Police Cadre": [
    "Bangla",
    "English",
    "Bangladesh Affairs",
    "International Affairs",
    "Mental Ability",
    "General Science and Technology",
    "Mathematical Reasoning",
    "Law and Ethics",
  ],
  "Foreign Affairs Cadre": [
    "Bangla",
    "English",
    "Bangladesh Affairs",
    "International Affairs",
    "Mental Ability",
    "General Science and Technology",
    "Mathematical Reasoning",
  ],
  "Audit and Accounts Cadre": [
    "Bangla",
    "English",
    "Bangladesh Affairs",
    "International Affairs",
    "Mental Ability",
    "General Science and Technology",
    "Accounting",
  ],
  "Information Cadre": [
    "Bangla",
    "English",
    "Bangladesh Affairs",
    "International Affairs",
    "Mental Ability",
    "General Science and Technology",
    "Computer Science and Information Technology",
  ],
  "Taxation Cadre": [
    "Bangla",
    "English",
    "Bangladesh Affairs",
    "International Affairs",
    "Mental Ability",
    "General Science and Technology",
    "Accounting",
  ],
  "Cooperative Cadre": [
    "Bangla",
    "English",
    "Bangladesh Affairs",
    "International Affairs",
    "Mental Ability",
    "General Science and Technology",
    "Accounting",
  ],
  "Health Cadre": [
    "Bangla",
    "English",
    "Bangladesh Affairs",
    "International Affairs",
    "Mental Ability",
    "General Science and Technology",
    "Medical Science",
  ],
};

//All Programming Languages
List<String> popularLanguages = [
  'Python',
  'Java',
  'JavaScript',
  'C',
  'C++',
  'C#',
  'PHP',
  'Ruby',
  'Swift',
  'Objective-C',
  'Kotlin',
  'TypeScript',
  'Go',
  'Rust',
  'Scala',
  'Lua',
  'Perl',
  'R',
  'SQL',
  'MATLAB',
  'Shell Scripting (Bash)',
  'Visual Basic .NET',
  'Dart',
  'Julia',
  'Groovy',
];
