name: super_notes
version: 0.0.1+1
publish_to: none
description: Discover a world of high-quality notes with Super Notes. Browse, search, and download notes for every level of education and preparation.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  super_ui_kit:
    path: ../
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  realm: ^1.0.2
  flutter_native_splash: ^2.2.19
  path_provider: ^2.0.5
  water_drop_nav_bar: ^2.2.0+5
  auto_animated: ^3.1.0
  flutter_cached_pdfview: ^0.4.1
  pdf: ^3.7.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
   - assets/config/
   - assets/img/
   - assets/animations/
   - assets/locales/

flutter_native_splash:
  color: "#e1f5fe"
  #background_image: "assets/background.png"
  image: assets/img/app_icon.png
  color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  image_dark: assets/img/app_icon.png
  #branding_dark: assets/dart_dark.png

  android_12:
    image: assets/img/app_icon.png

  # Splash screen background color.
    color: "#42a5f5"

  # App icon background color.
    icon_background_color: "#eeeeee"

  #image_dark: assets/android12splash-invert.png
  #color_dark: "#042a49"
    #icon_background_color_dark: "#111111"

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  #ios: false
  #web: false

  # Platform specific images can be specified with the following parameters, which will override
  # the respective parameter.  You may specify all, selected, or none of these parameters:
  #color_android: "#42a5f5"
  #color_dark_android: "#042a49"
  #color_ios: "#42a5f5"
  #color_dark_ios: "#042a49"
  #color_web: "#42a5f5"
  #color_dark_web: "#042a49"
  #image_android: assets/splash-android.png
  #image_dark_android: assets/splash-invert-android.png
  #image_ios: assets/splash-ios.png
  #image_dark_ios: assets/splash-invert-ios.png
  #image_web: assets/splash-web.png
  #image_dark_web: assets/splash-invert-web.png
  #background_image_android: "assets/background-android.png"
  #background_image_dark_android: "assets/dark-background-android.png"
  #background_image_ios: "assets/background-ios.png"
  #background_image_dark_ios: "assets/dark-background-ios.png"
  #background_image_web: "assets/background-web.png"
  #background_image_dark_web: "assets/dark-background-web.png"
  #branding_android: assets/brand-android.png
  #branding_dark_android: assets/dart_dark-android.png
  #branding_ios: assets/brand-ios.png
  #branding_dark_ios: assets/dart_dark-ios.png

  #android_gravity: center
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  #android_screen_orientation: sensorLandscape
  fullscreen: true

  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'

